### ISSUE TITLE
Display issue with timestamps

### ISSUE THREAD

**Issue by novoid** [yantar92/org#1]
Hi!
Emacs 26.1 and 26.3, latest commit from this repo (faf9039c7).

When I start typing right after an inactive or active time-stamp (without any space), the following text is shown with the same highlighting color as the time-stamp.

![Screenshot_2020-12-06_11-59-38 org display issue with time-stamp](https://user-images.githubusercontent.com/727493/101278283-a2d14300-37ba-11eb-9452-f6e7e02142fa.png)

When prepending the line with ": " it does not switch to "being displayed as comment, making syntax characters visible":

![Screenshot_2020-12-06_12-01-34 display issue 2del](https://user-images.githubusercontent.com/727493/101278318-d01df100-37ba-11eb-849f-ede6455d14bd.png)

**Comment by yantar92** [comment]
Can you try to reproduce using `cd /path/to/clones/org/folder/; emacs -Q -L ./lisp -l org`?

I can reproduce the same issue with my own config, but cannot with the above command. If you confirm that the issue is also with your config, there should be some external package affecting the fontification.

**EDIT**: Actually, I cannot reproduce it on my config either. I confused line highlighting with the timestamp formatting.

**Comment by novoid** [comment]
First of all: this results in `Eager macro-expansion failure: (error "rx form ‘regex’ requires args satisfying ‘stringp’")` within `*Messages*`.

Secondly, I can not reproduce the issue after running `cd /path/to/clones/org/folder/; emacs -Q -L ./lisp -l org`. Nice to know a way of being able to check these things.

I close the issue as I don't see a viable way of debugging it with my (complex) configuration.

**Comment by yantar92** [comment]
> close the issue as I don't see a viable way of debugging it with my (complex) configuration.

You may try to use https://github.com/Malabarba/elisp-bug-hunter It saved me a lot of debugging time in the past. My config is [not simple](https://github.com/yantar92/emacs-config/blob/master/config.org) either :)

**Comment by novoid** [comment]
Oh, thanks for the tip!

I guess this is golden in most cases. However, in many cases it can't work since I believe that it requires more than that when a workflow (which is broken) depends on several packages that get's disabled by automatic bisecting.

I just installed the package, made it run (I've got a literate config myself) and bisected an issue (not this one). It ran 10 times, half of the time, the workflow was broken because of missing packages or config. After the 10th run, it ended with "cl--assertion-failed: Assertion failed: ret-val".

I also ran it for *this* issue and it returned:
```
  The assertion returned the following value here:
    t
  Caused by the following expression:
    (org-expiry-insinuate)
```

Oh, this is surprising to me as far as I understand the implications of `org-expiry-insinuate`.

However, I disabled the line in my config, restarted Emacs and the issue still persists.

Anyway: thanks for the tip - it might come in handy in other cases.

**Comment by yantar92** [comment]
> I guess this is golden in most cases. However, in many cases it can't work since I believe that it requires more than that when a workflow (which is broken) depends on several packages that get's disabled by automatic bisecting.

If the issue is caused by specific packages in combination with this
branch, please report what packages are causing the problem. I will try
to debug and see it I can fix the problem on the org-mode side or I can
submit bug report to the package maintainer.

> I also ran it for *this* issue and it returned:
> ```
>   The assertion returned the following value here:
>     t
>   Caused by the following expression:
>     (org-expiry-insinuate)
> ```

I cannot reproduce it on my side.

> However, I disabled the line in my config, restarted Emacs and the issue still persists.

I guess there was no reason to stop. You can keep bisecting until the
issue disappears. I personally prefer to do interactive bisection and
disable suspicious packages manually. I sometimes get similar situation
when the result of bisection is not correct. Then, I just continue
debugging with the flagged packages disabled or moved upwards in the
emacs config. After several iterations (depending on the complexity), I
can narrow down the issue to few packages (possibly interacting with
each other in bizarre ways). The final pass is constructing minimal
config sufficient to run the suspected packages. If you get to that
point and share that minimal config, I can help to debug further.
