### ISSUE TITLE
move-end-of-line + newline-and-indent behaves differently

### ISSUE THREAD

**Issue by dakra** [yantar92/org#18]
I have a keybinding to `crux-smart-open-line` which inserts a blank
newline in the line below and moves the cursor there.
The full function definition is very simple:

```emacs-lisp
(defun crux-smart-open-line (arg)
  "Insert an empty line after the current line.
Position the cursor at its beginning, according to the current mode.

With a prefix ARG open line above the current line."
  (interactive "P")
  (if arg
      (crux-smart-open-line-above)
    (move-end-of-line nil)
    (newline-and-indent)))
```

When calling this function in the master branch on a folded heading
I'll get a new line under it with the cursor in there.

With org fold I get a newline but the new line is still folded and invisible
until I type something.

------

Now that I've put it into words, I would even say the `org-fold`
branch makes more sense than `master` as in `master` the
heading stays collapsed but only the newline and text after
is visible until I toggle the headline.

I'll still post this issue and close it right away so
you're aware that there is a difference.

Thanks for your work :)

**Comment by yantar92** [comment]
> I'll still post this issue and close it right away so
you're aware that there is a difference.

Thanks for reporting! For now, org-fold deliberately does not reveal text inserted in the middle of a folded region. In fact, I had to implement re-hiding since inserted text would be visible by default because of the way how text properties work in Emacs. The text is revealed only when structure of folded region is broken (for example, try to remove ":" in a folded drawer).

In the future, I may consider user customisation of the revealing/hiding changed text. Current implementation of `org-fold-check-before-invisible-edit` is very limited (it is just copied from the master version) - it covers only a small set of known interactive commands. If you have any ideas what should be changed, feel free to let me know. Though they will probably need to be discussed in the org-mode mailing list as well.
